### ISSUE TITLE
Asynchronous Submit Feature

### ISSUE THREAD

**Issue by jkmuka** [pstanoev/simple-svelte-autocomplete#39] opened 2021-02-24 20:59 UTC
In this scenario, async calls are made to a server api which searches in cache. If no results are returned, does this component allow a submit event to the server via user pressing enter key or some button?

**Comment by pstanoev** [comment] 2021-04-27 16:14
Seems like duplicate of #23 
For now we don't plan adding a feature to accept unlisted items.

**Comment by pstanoev** [comment] 2021-07-15 17:38
Kind of supported in version 2.1. check the demo page, advances usage.

**Closed by pstanoev** 2021-07-15 17:38 UTC
